apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN airconnect
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: airconnect
    location: lan
  name: airconnect
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/airconnect
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: airconnect
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN airconnect
      creationTimestamp: null
      labels:
        k8s-app: airconnect
        location: lan
      name: airconnect
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-airconnect
        imagePullPolicy: Always
        name: airconnect
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
